[package]
name = "makepad-component"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "UI components for Makepad applications"

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
makepad-widgets = { workspace = true }
